<#
.SYNOPSIS
    Reads adcs.env and returns its keys as a hashtable.

.DESCRIPTION
    Every other script in this folder calls this instead of carrying site values
    of its own, which is what lets them be plain PowerShell rather than Jinja
    templates - editable and lintable as they sit.

    adcs.env is generated by bootstrap.py from config.env. Copy it to the
    Windows host next to these .ps1 files.

    An environment variable of the same name wins over the file, so a one-off
    override works without editing anything:

        $env:ADCS_HOST = 'dc02.example.internal'

    which mirrors how bootstrap.py treats config.env on the Linux side.

.PARAMETER ConfigFile
    Path to adcs.env. Defaults to $env:ADCS_ENV_FILE, then adcs.env in this
    script's own directory.

.PARAMETER Require
    Keys that must be present and non-empty. Missing ones are reported together
    rather than one failure at a time.

.EXAMPLE
    $cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -Require @('ADCS_HOST')
    $cfg.ADCS_HOST
#>

[CmdletBinding()]
param(
    [string]$ConfigFile,
    [string[]]$Require = @()
)

$ErrorActionPreference = 'Stop'

if (-not $ConfigFile)  { $ConfigFile = $env:ADCS_ENV_FILE }
if (-not $ConfigFile)  { $ConfigFile = Join-Path $PSScriptRoot 'adcs.env' }

if (-not (Test-Path -LiteralPath $ConfigFile)) {
    throw "adcs.env not found at '$ConfigFile'. Render it with ./bootstrap.py and copy rendered/ad/adcs.env next to these scripts, or pass -ConfigFile."
}

$config = @{}
foreach ($line in Get-Content -LiteralPath $ConfigFile) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }

    $split = $trimmed.IndexOf('=')
    if ($split -lt 1) { continue }

    $key   = $trimmed.Substring(0, $split).Trim()
    $value = $trimmed.Substring($split + 1).Trim()

    # Strip one layer of matching quotes, the way config.env is parsed.
    if ($value.Length -ge 2) {
        foreach ($q in @('"', "'")) {
            if ($value.StartsWith($q) -and $value.EndsWith($q)) {
                $value = $value.Substring(1, $value.Length - 2)
                break
            }
        }
    }

    # A real environment variable beats the file.
    $fromEnv = [Environment]::GetEnvironmentVariable($key)
    if ($fromEnv) { $value = $fromEnv }

    $config[$key] = $value
}

$missing = @($Require | Where-Object { -not $config.ContainsKey($_) -or -not $config[$_] })
if ($missing.Count) {
    throw "adcs.env ($ConfigFile) is missing: $($missing -join ', '). Set them in config.env and re-run ./bootstrap.py."
}

$config
