<#
.SYNOPSIS
    Runs the whole AD CS chain in order on a fresh CA host: CA role, web
    enrollment gMSA, and the /certsrv HTTPS endpoint the cert-manager
    adcs-issuer needs.

.DESCRIPTION
    Run on the CA host from an elevated session, as a member of Enterprise
    Admins. Copy the whole rendered/ad folder across - this calls its siblings
    from $PSScriptRoot and will not run without them.

    In this domain the CA host is also a domain controller, so all three steps
    belong on one machine. The gMSA step normally needs a reboot before the web
    enrollment step (the host has to see its new group membership); this script
    purges the computer's Kerberos tickets instead, and only asks for a reboot
    if that was not enough.

    THIS IS A ONE-SHOT, FROM-SCRATCH INSTALL. Every step assumes nothing it
    creates already exists, so re-running after a partial failure will fail on
    whatever the first run did create. Roll back to the snapshot the CA step
    takes, and start again.

.NOTES
    The workstation half of the deployment is not run from here - it needs oc
    and helm against the OKD cluster. The commands are printed at the end.
#>

# Site values live in adcs.env (generated by bootstrap.py from config.env);
# this script is ordinary PowerShell and is meant to be edited directly.

[CmdletBinding()]
param(
    # adcs.env to read. Defaults to $env:ADCS_ENV_FILE, then adcs.env
    # beside this script.
    [string]$ConfigFile,

    [bool]$SnapshotFirst = $true,

    [string]$CaHost,
    [string]$GmsaName,
    [string]$AdcsUrl
)

$ErrorActionPreference = 'Stop'

# Site values come from adcs.env, so this file stays generic. Anything passed
# on the command line wins over the file.
$cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -ConfigFile $ConfigFile -Require @('ADCS_HOST', 'ADCS_URL', 'ADCS_WEB_GMSA_NAME')
if (-not $CaHost)   { $CaHost   = $cfg.ADCS_HOST }
if (-not $GmsaName) { $GmsaName = $cfg.ADCS_WEB_GMSA_NAME }
if (-not $AdcsUrl)  { $AdcsUrl  = $cfg.ADCS_URL }

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not ([Security.Principal.WindowsPrincipal]$identity).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell session."
}

# This script assumes the CA and the web enrollment pages live on this machine.
# Split those across hosts and the steps have to be run separately, on each.
$shortName = $CaHost.Split('.')[0]
if ($env:COMPUTERNAME -ne $shortName) {
    throw "This host is $env:COMPUTERNAME but ADCS_HOST is $CaHost. Run this on $shortName, or run the three scripts individually on the right hosts."
}

$steps = @(
    @{ Name = 'CA'
       Script = 'Install-AdcsCertificationAuthority.ps1'
       Args = @{ ConfigFile = $ConfigFile; SnapshotFirst = $SnapshotFirst }
       Title = 'AD CS role and Enterprise Root CA' }
    @{ Name = 'EnrollAccount'
       Script = 'New-AdcsEnrollmentAccount.ps1'
       Args = @{ ConfigFile = $ConfigFile }
       Title = 'Enrolment account, and its Enroll right on the template' }
    @{ Name = 'Gmsa'
       Script = 'New-AdcsWebEnrollmentGmsa.ps1'
       Args = @{ ConfigFile = $ConfigFile }
       Title = 'gMSA for the /certsrv application pool' }
    @{ Name = 'WebEnrollment'
       Script = 'Install-AdcsWebEnrollment.ps1'
       Args = @{ ConfigFile = $ConfigFile }
       Title = 'Publish /certsrv over HTTPS' }
)

# Fail before doing anything if the folder was copied across incompletely -
# discovering this between steps would leave the CA half-configured, and there
# is no safe re-run.
foreach ($step in $steps) {
    $step.Path = Join-Path $PSScriptRoot $step.Script
    if (-not (Test-Path $step.Path)) {
        throw "Missing $($step.Script) in $PSScriptRoot. Copy the whole rendered/ad folder, not just this file."
    }
}

function Write-Banner {
    param([string]$Text)
    Write-Host ""
    Write-Host ("=" * 72)
    Write-Host "  $Text"
    Write-Host ("=" * 72)
}

foreach ($step in $steps) {
    Write-Banner "$($step.Name) - $($step.Title)"

    $stepArgs = $step.Args
    & $step.Path @stepArgs

    # --- interlude: make the gMSA usable on this host before the next step ---
    if ($step.Name -eq 'Gmsa') {
        Write-Banner "Gmsa - install on this host"

        Import-Module ActiveDirectory
        Install-ADServiceAccount -Identity $GmsaName

        # The computer only learns it is in the new retrieval group when it gets
        # a fresh TGT. Purging the SYSTEM logon session's tickets forces that
        # without a reboot. 0x3e7 is the well-known LUID for the computer account.
        Write-Host "Purging the computer account's Kerberos tickets..."
        & klist.exe purge -li 0x3e7 | Out-Null

        if (-not (Test-ADServiceAccount -Identity $GmsaName)) {
            Write-Warning "Test-ADServiceAccount still fails for $GmsaName."
            Write-Warning "The ticket refresh was not enough - reboot, then run:"
            Write-Warning "    .\Install-AdcsWebEnrollment.ps1"
            exit 1
        }
        Write-Host "gMSA $GmsaName is usable on this host."
    }
}

# ------------------------------------------------------------------- summary

Write-Banner "Done"

try {
    $resp = Invoke-WebRequest -Uri "$AdcsUrl/" -UseDefaultCredentials -UseBasicParsing -TimeoutSec 20
    Write-Host "$AdcsUrl -> $($resp.StatusCode); the issuer's endpoint is up."
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 401) {
        Write-Host "$AdcsUrl -> 401; endpoint is up and asking for credentials, which is correct."
    } else {
        Write-Warning "$AdcsUrl is not answering as expected: $($_.Exception.Message)"
    }
}

Write-Host ""
Write-Host "Now, from the workstation with oc and helm:"
Write-Host ""
Write-Host "  scripts/helm/certificate-manager/deploy-cert-man.sh"
Write-Host "  scripts/helm/certificate-manager/configure-clusterissuer.sh"
Write-Host ""
Write-Host "The second checks $AdcsUrl before it creates anything."
