<#
.SYNOPSIS
    Installs the AD CS Certification Authority role service and configures an
    Enterprise Root CA.

.DESCRIPTION
    Run on the intended CA host as a member of Enterprise Admins (an Enterprise
    CA writes its enrollment object into the forest configuration partition, so
    Domain Admins alone is not enough).

    Assumes a clean host with no CA on it. It does not check for, or adapt to,
    an existing installation - against a host that already has a CA it will fail
    rather than reconfigure one, which is the intended behaviour.

.NOTES
    The CA service (CertSvc) runs as LocalSystem on an Enterprise CA and does
    NOT support a gMSA. gMSAs apply to the IIS application pools that front the
    CA - see New-AdcsWebEnrollmentGmsa.ps1 and New-AdcsCesGmsa.ps1.

    SNAPSHOT: -SnapshotFirst (on by default) asks Proxmox to snapshot this VM
    before anything is changed. Taking a snapshot of a running DC is safe.
    ROLLING ONE BACK IS NOT, and is not something this script does.

    Restoring a DC to an earlier point can cause a USN rollback: the restored DC
    reissues update sequence numbers its replication partners have already seen,
    and those partners then silently ignore its later changes. Windows Server
    2012+ mitigates this with VM-GenerationID, which Proxmox exposes, so
    rollback is supported rather than merely survivable - but it is a recovery
    action. Check replication with `repadmin /showrepl` and `dcdiag` afterwards.
#>

# Site values live in adcs.env (generated by bootstrap.py from config.env);
# this script is ordinary PowerShell and is meant to be edited directly.

[CmdletBinding()]
param(
    # adcs.env to read. Defaults to $env:ADCS_ENV_FILE, then adcs.env
    # beside this script.
    [string]$ConfigFile,

    [string]$CaName,
    [int]$KeyLength        = 4096,
    [string]$HashAlgorithm = 'SHA256',
    [int]$ValidityYears    = 10,

    # Snapshot this VM through the Proxmox API before changing anything.
    # Pass -SnapshotFirst:$false to skip it (and say why in your change record).
    [bool]$SnapshotFirst = $true,

    [string]$PveHost,
    [string]$PveNode,
    [int]$PveVmid,
    [string]$PveTokenId,

    # Including RAM makes a rollback resume rather than cold-boot. Off by
    # default: a cold boot puts the DC through normal startup, which is where
    # the VM-GenerationID check runs.
    [bool]$IncludeRam = $false,

    # Proxmox uses a self-signed certificate unless you have replaced it.
    [bool]$PveSkipCertCheck = $true
)

$ErrorActionPreference = 'Stop'

# Site values come from adcs.env, so this file stays generic. Anything passed
# on the command line wins over the file.
$cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -ConfigFile $ConfigFile -Require @('ADCS_CA_NAME', 'PVE_API_HOST', 'PVE_API_TOKEN_ID', 'PVE_DC_VMID', 'PVE_NODE')
if (-not $CaName)      { $CaName     = $cfg.ADCS_CA_NAME }
if (-not $PveHost)     { $PveHost    = $cfg.PVE_API_HOST }
if (-not $PveNode)     { $PveNode    = $cfg.PVE_NODE }
if (-not $PveVmid)     { $PveVmid    = [int]$cfg.PVE_DC_VMID }
if (-not $PveTokenId)  { $PveTokenId = $cfg.PVE_API_TOKEN_ID }

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not ([Security.Principal.WindowsPrincipal]$identity).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell session."
}

# -------------------------------------------------------------------- snapshot

function New-PveSnapshot {
    [CmdletBinding(SupportsShouldProcess = $true)]
    param(
        [Parameter(Mandatory)][string]$ApiHost,
        [Parameter(Mandatory)][string]$Node,
        [Parameter(Mandatory)][int]$Vmid,
        [Parameter(Mandatory)][string]$TokenId,
        [Parameter(Mandatory)][string]$TokenSecret,
        [Parameter(Mandatory)][string]$SnapName,
        [string]$Description = '',
        [bool]$IncludeRam = $false,
        [bool]$SkipCertificateCheck = $true,
        [int]$TimeoutSec = 900
    )

    # Windows Server ships PowerShell 5.1, where Invoke-RestMethod has no
    # -SkipCertificateCheck; the validation callback is the 5.1 equivalent.
    # 5.1 also still negotiates TLS 1.0 by default, which Proxmox refuses.
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $extra = @{}
    if ($SkipCertificateCheck) {
        if ($PSVersionTable.PSVersion.Major -ge 6) {
            $extra['SkipCertificateCheck'] = $true
        } else {
            [Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
        }
    }

    try {
        $base    = "https://${ApiHost}:8006/api2/json"
        $headers = @{ Authorization = "PVEAPIToken=$TokenId=$TokenSecret" }
        $body    = @{ snapname = $SnapName; vmstate = [int]$IncludeRam }
        if ($Description) { $body['description'] = $Description }

        if (-not $PSCmdlet.ShouldProcess("$Node/$Vmid", "Create snapshot '$SnapName'")) {
            return
        }

        Write-Host "Snapshotting $Node/$Vmid as '$SnapName'..."
        $resp = Invoke-RestMethod -Method Post -Headers $headers -Body $body `
                                  -Uri "$base/nodes/$Node/qemu/$Vmid/snapshot" @extra
        $upid = $resp.data

        # Proxmox returns a task id immediately; the snapshot is not taken until
        # that task finishes. Returning here would race the role install against it.
        $encoded  = [uri]::EscapeDataString($upid)
        $deadline = (Get-Date).AddSeconds($TimeoutSec)
        do {
            Start-Sleep -Seconds 3
            $task = Invoke-RestMethod -Method Get -Headers $headers `
                                      -Uri "$base/nodes/$Node/tasks/$encoded/status" @extra
        } while ($task.data.status -eq 'running' -and (Get-Date) -lt $deadline)

        if ($task.data.status -ne 'stopped') {
            throw "Snapshot task did not finish within $TimeoutSec seconds (UPID $upid)."
        }
        if ($task.data.exitstatus -ne 'OK') {
            throw "Snapshot failed: $($task.data.exitstatus) (UPID $upid)."
        }
        Write-Host "Snapshot '$SnapName' complete."
    } finally {
        # Leaving validation disabled would silently affect every later HTTPS
        # call in this session.
        [Net.ServicePointManager]::ServerCertificateValidationCallback = $null
    }
}

if ($SnapshotFirst) {
    # The token secret is never baked into this file - it is a credential, and
    # these scripts get copied around. Set PVE_API_TOKEN or type it here.
    $tokenSecret = $env:PVE_API_TOKEN
    if (-not $tokenSecret) {
        $secure = Read-Host -AsSecureString "Proxmox API token secret for $PveTokenId"
        $bstr   = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
        try   { $tokenSecret = [Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) }
        finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
    }
    if (-not $tokenSecret) {
        throw "No Proxmox API token. Set `$env:PVE_API_TOKEN, or re-run with -SnapshotFirst:`$false to proceed without a snapshot."
    }

    New-PveSnapshot -ApiHost $PveHost -Node $PveNode -Vmid $PveVmid `
                    -TokenId $PveTokenId -TokenSecret $tokenSecret `
                    -SnapName ('preadcs-' + (Get-Date -Format 'yyyyMMdd-HHmmss')) `
                    -Description "Before AD CS role install ($CaName)" `
                    -IncludeRam $IncludeRam -SkipCertificateCheck $PveSkipCertCheck

    Remove-Variable tokenSecret
} else {
    Write-Warning "-SnapshotFirst:`$false - proceeding with no rollback point."
}

# ------------------------------------------------------------------ install

Write-Host "Installing role service ADCS-Cert-Authority..."
Install-WindowsFeature -Name ADCS-Cert-Authority -IncludeManagementTools | Out-Null

Import-Module ADCSDeployment

Write-Host "Configuring Enterprise Root CA '$CaName' ($KeyLength-bit, $HashAlgorithm, $ValidityYears years)..."
Install-AdcsCertificationAuthority `
    -CAType EnterpriseRootCA `
    -CACommonName $CaName `
    -KeyLength $KeyLength `
    -HashAlgorithmName $HashAlgorithm `
    -CryptoProviderName 'RSA#Microsoft Software Key Storage Provider' `
    -ValidityPeriod Years `
    -ValidityPeriodUnits $ValidityYears `
    -Force

Start-Service CertSvc

Write-Host ""
certutil -cainfo | Select-String -Pattern 'CA name|CA type|DNS Name'

Write-Host ""
Write-Host "Next:"
Write-Host "  New-AdcsWebEnrollmentGmsa.ps1     (on a DC, creates the app pool gMSA)"
Write-Host "  Install-AdcsWebEnrollment.ps1     (here, publishes /certsrv over HTTPS)"
