<#
.SYNOPSIS
    Installs and publishes the AD CS web enrollment pages (/certsrv) over HTTPS,
    which is the endpoint the cert-manager adcs-issuer talks to.

.DESCRIPTION
    Run on the CA host from an elevated session, as a member of Enterprise
    Admins, after Install-AdcsCertificationAuthority.ps1 and
    New-AdcsWebEnrollmentGmsa.ps1.

    Safe to re-run: existing IIS objects are reused. The http.sys certificate
    binding is re-pointed each time, so a re-run picks up a newly enrolled
    certificate.

.NOTES
    The adcs-issuer POSTs to <url>/certfnsh.asp and parses the HTML reply, so
    this role service - not CES, and not the CA alone - is what it depends on.
    It must be HTTPS: certsrv authenticates every request, so over plain HTTP
    the Kerberos exchange and the CSR both cross the network unprotected.
#>

# Site values live in adcs.env (generated by bootstrap.py from config.env);
# this script is ordinary PowerShell and is meant to be edited directly.

[CmdletBinding()]
param(
    # adcs.env to read. Defaults to $env:ADCS_ENV_FILE, then adcs.env
    # beside this script.
    [string]$ConfigFile,

    [string]$WebHost,
    [string]$Template,
    [string]$GmsaName,
    [string]$Netbios,

    [string]$AppPoolName = 'CertSrvAppPool',

    # Pass -UseGmsa:$false to leave the pool as ApplicationPoolIdentity.
    [bool]$UseGmsa = $true
)

$ErrorActionPreference = 'Stop'

# Site values come from adcs.env, so this file stays generic. Anything passed
# on the command line wins over the file.
$cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -ConfigFile $ConfigFile -Require @('ADCS_HOST', 'ADCS_TEMPLATE', 'AD_NETBIOS')
if (-not $WebHost)  { $WebHost  = $cfg.ADCS_HOST }
if (-not $Template) { $Template = $cfg.ADCS_TEMPLATE }
if (-not $GmsaName) { $GmsaName = $cfg.ADCS_WEB_GMSA_NAME }
if (-not $Netbios)  { $Netbios  = $cfg.AD_NETBIOS }

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not ([Security.Principal.WindowsPrincipal]$identity).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw "Run this from an elevated PowerShell session."
}

# ---------------------------------------------------------------- role service

Write-Host "Installing role service ADCS-Web-Enrollment..."
Install-WindowsFeature -Name ADCS-Web-Enrollment -IncludeManagementTools | Out-Null

Import-Module ADCSDeployment
Import-Module WebAdministration

# Installing the feature only puts the files on disk; this creates the /CertSrv
# application under the Default Web Site.
Write-Host "Configuring web enrollment..."
if (Test-Path 'IIS:\Sites\Default Web Site\CertSrv') {
    Write-Host "/certsrv application already present."
} else {
    Install-AdcsWebEnrollment -Force | Out-Null
}

# ------------------------------------------------------------- TLS certificate

# Requesting into LocalMachine\My submits as the computer account, and a stock
# template grants Enroll to Domain Admins and Enterprise Admins only - both
# user principals. A machine request is therefore refused outright:
#
#     CertEnroll::CX509Enrollment::Enroll: You do not have permission to request
#     this type of certificate. 0x80094012 (CERTSRV_E_TEMPLATE_DENIED)
#
# So grant this host's computer account Read + Enroll on the template first.
# Scoped to this one machine account rather than Domain Computers.
Import-Module ActiveDirectory
$ENROLL_RIGHT = [guid]'0e10c968-78fb-11d2-90d4-00c04f79dc55'
$templateDN = "CN=$Template,CN=Certificate Templates,CN=Public Key Services,CN=Services," +
              (Get-ADRootDSE).configurationNamingContext
if (-not (Test-Path "AD:$templateDN")) {
    throw "Certificate template '$Template' not found at $templateDN."
}

$machineSid = (Get-ADComputer -Identity $env:COMPUTERNAME).SID
$templateAcl = Get-Acl -Path "AD:$templateDN"
$templateAcl.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule(
    $machineSid,
    [System.DirectoryServices.ActiveDirectoryRights]::GenericRead,
    [System.Security.AccessControl.AccessControlType]::Allow)))
$templateAcl.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule(
    $machineSid,
    [System.DirectoryServices.ActiveDirectoryRights]::ExtendedRight,
    [System.Security.AccessControl.AccessControlType]::Allow,
    $ENROLL_RIGHT)))
Set-Acl -Path "AD:$templateDN" -AclObject $templateAcl
Write-Host "Granted $env:COMPUTERNAME`$ Read + Enroll on the '$Template' template."

# The CA caches template definitions; re-reading them picks the new ACE up
# without waiting for its own refresh interval.
& certutil.exe -pulse | Out-Null
Start-Sleep -Seconds 5

Write-Host "Enrolling a '$Template' certificate for $WebHost..."
$enrolled = Get-Certificate -Template $Template `
                            -SubjectName "CN=$WebHost" `
                            -DnsName $WebHost `
                            -CertStoreLocation Cert:\LocalMachine\My
$cert = $enrolled.Certificate
Write-Host "Enrolled $($cert.Thumbprint)."

if (-not (Get-WebBinding -Name 'Default Web Site' -Protocol https -Port 443)) {
    New-WebBinding -Name 'Default Web Site' -Protocol https -Port 443
}
# The http.sys SSL binding outlives the IIS web binding - removing the site
# binding leaves the certificate mapping behind, and New-Item then fails with
# "Cannot create a file when that file already exists". Re-pointing it is also
# what makes a re-run pick up a newly enrolled certificate.
if (Test-Path 'IIS:\SslBindings\0.0.0.0!443') {
    Remove-Item -Path 'IIS:\SslBindings\0.0.0.0!443' -Force
}
New-Item -Path 'IIS:\SslBindings\0.0.0.0!443' -Value $cert | Out-Null
Write-Host "Bound $($cert.Thumbprint) to 0.0.0.0:443."

# ------------------------------------------------------------- application pool

# /certsrv ships in DefaultAppPool. A dedicated pool means the gMSA identity
# below applies to certsrv alone rather than every app on the site. certsrv is
# classic ASP, so the pool has to be in Classic pipeline mode.
if (-not (Test-Path "IIS:\AppPools\$AppPoolName")) {
    New-WebAppPool -Name $AppPoolName | Out-Null
}
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name managedPipelineMode -Value 'Classic'
Set-ItemProperty 'IIS:\Sites\Default Web Site\CertSrv' -Name applicationPool -Value $AppPoolName

if ($UseGmsa -and $GmsaName) {
    Import-Module ActiveDirectory
    $account = $Netbios + '\' + $GmsaName + '$'
    if (-not (Test-ADServiceAccount -Identity $GmsaName)) {
        throw "Test-ADServiceAccount failed for $GmsaName. Run Install-ADServiceAccount -Identity $GmsaName first (and reboot if the host was only just added to the retrieval group)."
    }
    # identityType 3 = SpecificUser. A gMSA takes an empty password - Windows
    # fetches it from AD.
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.identityType -Value 3
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.userName -Value $account
    Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.password -Value ''
    Write-Host "Application pool runs as $account."
}

# ------------------------------------------------------------- authentication

$app = 'Default Web Site/CertSrv'

Set-WebConfigurationProperty -PSPath 'IIS:\' -Location $app `
    -Filter '/system.webServer/security/authentication/anonymousAuthentication' `
    -Name enabled -Value $false

Set-WebConfigurationProperty -PSPath 'IIS:\' -Location $app `
    -Filter '/system.webServer/security/authentication/windowsAuthentication' `
    -Name enabled -Value $true

if ($UseGmsa -and $GmsaName) {
    # The HTTP SPNs live on the gMSA, not the computer account, so IIS has to
    # use the app pool identity to decrypt the service ticket. Without this
    # every request returns 401 no matter how correct the SPNs are.
    Set-WebConfigurationProperty -PSPath 'IIS:\' -Location $app `
        -Filter '/system.webServer/security/authentication/windowsAuthentication' `
        -Name useAppPoolCredentials -Value $true
}

# Negotiate first so Kerberos is preferred; NTLM stays as the fallback the
# adcs-issuer uses if it cannot get a ticket.
#
# Set the whole collection rather than clearing it and adding entries back:
# clearing removes only this location's entries, after which the parent's
# providers are inherited again, so the adds collide with what came back -
#   Cannot add duplicate collection entry of type 'add' with unique key
#   attribute 'value' set to 'Negotiate'
Set-WebConfigurationProperty -PSPath 'IIS:\' -Location $app `
    -Filter '/system.webServer/security/authentication/windowsAuthentication/providers' `
    -Name '.' -Value @(@{ value = 'Negotiate' }, @{ value = 'NTLM' })

Set-WebConfigurationProperty -PSPath 'IIS:\' -Location $app `
    -Filter '/system.webServer/security/access' -Name sslFlags -Value 'Ssl'

Restart-WebAppPool -Name $AppPoolName
iisreset /noforce | Out-Null

# -------------------------------------------------------------------- verify

Write-Host ""
$url = "https://$WebHost/certsrv/"
try {
    $resp = Invoke-WebRequest -Uri $url -UseDefaultCredentials -UseBasicParsing -TimeoutSec 20
    Write-Host "GET $url -> $($resp.StatusCode) (authenticated OK)"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code) { Write-Warning "GET $url -> $code" }
    else { Write-Warning "GET $url failed: $($_.Exception.Message)" }
}

Write-Host ""
Write-Host "Set in config.env:  ADCS_URL=https://$WebHost/certsrv"
Write-Host "Then, from the workstation:"
Write-Host "  scripts/helm/certificate-manager/configure-clusterissuer.sh"
