<#
.SYNOPSIS
    Creates a group Managed Service Account (gMSA) to run the AD CS web
    enrollment (/certsrv) IIS application pool.

.DESCRIPTION
    Run on a domain controller, or any domain member with RSAT-AD-PowerShell, as
    a member of Domain Admins.

    Safe to re-run: the KDS root key, retrieval group, group membership and the
    account itself are each created only if absent, and an existing account is
    updated in place.

    This creates the account in AD only. Installing it on the web enrollment
    host and binding it to the application pool happen there -
    Install-AdcsWebEnrollment.ps1 does both.

.NOTES
    The CA service (CertSvc) itself runs as LocalSystem on an Enterprise CA and
    cannot be moved to a gMSA. This account is for the IIS application pool that
    serves /certsrv, which is the endpoint the cert-manager adcs-issuer talks to.

    This is a different account from the one New-AdcsCesGmsa.ps1 creates. CES
    (ADCS-Enroll-Web-Svc) and web enrollment (ADCS-Web-Enrollment) are separate
    role services with separate application pools; the adcs-issuer needs the
    latter.
#>

# Site values live in adcs.env (generated by bootstrap.py from config.env);
# this script is ordinary PowerShell and is meant to be edited directly.

[CmdletBinding()]
param(
    # adcs.env to read. Defaults to $env:ADCS_ENV_FILE, then adcs.env
    # beside this script.
    [string]$ConfigFile,

    [string]$Name,
    [string]$GroupName,
    [string]$WebHost,
    [string]$CaHost,
    [string]$GroupPath
)

$ErrorActionPreference = 'Stop'

# Site values come from adcs.env, so this file stays generic. Anything passed
# on the command line wins over the file.
$cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -ConfigFile $ConfigFile -Require @('ADCS_HOST', 'ADCS_WEB_GMSA_NAME', 'ADCS_WEB_GROUP_NAME', 'AD_GROUP_BASE_DN')
if (-not $Name)      { $Name      = $cfg.ADCS_WEB_GMSA_NAME }
if (-not $GroupName) { $GroupName = $cfg.ADCS_WEB_GROUP_NAME }
if (-not $WebHost)   { $WebHost   = $cfg.ADCS_HOST }
if (-not $CaHost)    { $CaHost    = $cfg.ADCS_HOST }
if (-not $GroupPath) { $GroupPath = $cfg.AD_GROUP_BASE_DN }

Import-Module ActiveDirectory

# gMSA passwords are derived from a KDS root key. A newly added key is normally
# only usable after 10 hours (it waits for AD replication); backdating the
# effective time is the standard workaround on a small or single-DC domain.
if (Get-KdsRootKey) {
    Write-Host "Forest already has a KDS root key."
} else {
    Write-Host "Adding the forest KDS root key (backdated so it is usable immediately)."
    Add-KdsRootKey -EffectiveTime ((Get-Date).AddHours(-10)) | Out-Null
}

# Only computers in this group may retrieve the gMSA password. Using a group
# rather than naming the host directly means adding a second web enrollment
# server later requires no change to the account itself.
$group = Get-ADGroup -Filter "Name -eq '$GroupName'"
if ($group) {
    Write-Host "Group $GroupName already exists."
} else {
    $group = New-ADGroup -Name $GroupName -GroupScope Global -GroupCategory Security -Path $GroupPath -PassThru
    Write-Host "Created group $GroupName."
}

$webShort    = $WebHost.Split('.')[0]
$webComputer = Get-ADComputer -Identity $webShort
$members     = @(Get-ADGroupMember -Identity $group | Select-Object -ExpandProperty distinguishedName)
if ($members -contains $webComputer.DistinguishedName) {
    Write-Host "$webShort is already in $GroupName."
} else {
    Add-ADGroupMember -Identity $group -Members $webComputer
    Write-Host "Added $webShort to $GroupName."
}

# certsrv is reached over HTTP(S), so the account needs HTTP SPNs on both the
# FQDN and the short name for Kerberos to succeed either way the client asks.
# Moving these SPNs onto the gMSA is what makes useAppPoolCredentials necessary
# on the IIS side.
if (Get-ADServiceAccount -Filter "Name -eq '$Name'") {
    Write-Host "gMSA $Name already exists - updating it."
    Set-ADServiceAccount -Identity $Name `
        -PrincipalsAllowedToRetrieveManagedPassword $group `
        -ServicePrincipalNames @{ Replace = @("HTTP/$WebHost", "HTTP/$webShort") } `
        -KerberosEncryptionType AES128, AES256
} else {
    New-ADServiceAccount -Name $Name `
        -DNSHostName $WebHost `
        -Description 'Runs the AD CS web enrollment (/certsrv) IIS application pool' `
        -PrincipalsAllowedToRetrieveManagedPassword $group `
        -ServicePrincipalNames @("HTTP/$WebHost", "HTTP/$webShort") `
        -KerberosEncryptionType AES128, AES256
    Write-Host "Created gMSA $Name."
}

# When /certsrv runs on the CA itself it submits over local RPC and needs no
# delegation. Split across hosts it impersonates the caller to the CA, so it
# needs constrained delegation to the CA's RPC interface - without it the client
# authenticates to IIS and the request then fails inside the web service.
if ($WebHost -ne $CaHost) {
    Set-ADServiceAccount -Identity $Name -Replace @{
        'msDS-AllowedToDelegateTo' = @("rpcss/$CaHost", "HOST/$CaHost")
    }
    Write-Host "Web enrollment is remote from the CA - added constrained delegation to $CaHost."
}

$account = (Get-ADDomain).NetBIOSName + '\' + $Name + '$'

Write-Host ""
Write-Host "Next, on ${WebHost}:"
Write-Host ""
Write-Host "  # the host must refresh its Kerberos ticket to see the new group membership"
Write-Host "  Restart-Computer"
Write-Host ""
Write-Host "  Install-ADServiceAccount -Identity $Name"
Write-Host "  Test-ADServiceAccount    -Identity $Name     # must return True before continuing"
Write-Host ""
Write-Host "  .\Install-AdcsWebEnrollment.ps1"
Write-Host ""
Write-Host "Because the HTTP SPNs belong to $account rather than the computer"
Write-Host "account, IIS must decrypt Kerberos tickets with the app pool identity."
Write-Host "Install-AdcsWebEnrollment.ps1 sets useAppPoolCredentials for you."
