<#
.SYNOPSIS
    Creates a group Managed Service Account (gMSA) to run the AD CS Certificate
    Enrollment Web Service (CES).

.DESCRIPTION
    Run on a domain controller, or any domain member with RSAT-AD-PowerShell,
    as a member of Domain Admins.

    Assumes the group and account do not exist yet, and that the forest already
    has a KDS root key - New-AdcsWebEnrollmentGmsa.ps1 adds one, or add it
    yourself with:

        Add-KdsRootKey -EffectiveTime ((Get-Date).AddHours(-10))

    This creates the account in AD only. Installing it on the CES host and
    binding it to the CES application pool happen on that host; the commands are
    printed at the end.

.NOTES
    CES is not the same thing as the certsrv web enrollment pages, and the
    cert-manager adcs-issuer does not use it - it talks to /certsrv (role
    service ADCS-Web-Enrollment). This script is here for clients that enrol
    over the WS-Trust API; it is not part of the adcs-issuer path.
#>

# Site values live in adcs.env (generated by bootstrap.py from config.env);
# this script is ordinary PowerShell and is meant to be edited directly.

[CmdletBinding()]
param(
    # adcs.env to read. Defaults to $env:ADCS_ENV_FILE, then adcs.env
    # beside this script.
    [string]$ConfigFile,

    [string]$Name,
    [string]$CesHost,
    [string]$CaHost,
    [string]$GroupName,
    [string]$GroupPath,
    [string]$CaName
)

$ErrorActionPreference = 'Stop'

# Site values come from adcs.env, so this file stays generic. Anything passed
# on the command line wins over the file.
$cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -ConfigFile $ConfigFile
if (-not $Name)      { $Name      = $cfg.CES_GMSA_NAME }
if (-not $CesHost)   { $CesHost   = $cfg.CES_HOST }
if (-not $CaHost)    { $CaHost    = $cfg.ADCS_HOST }
if (-not $GroupName) { $GroupName = $cfg.CES_GROUP_NAME }
if (-not $GroupPath) { $GroupPath = $cfg.AD_GROUP_BASE_DN }
if (-not $CaName)    { $CaName    = $cfg.ADCS_CA_NAME }

Import-Module ActiveDirectory

# Only computers in this group may retrieve the gMSA password. Using a group
# rather than naming the host directly means adding a second CES server later
# requires no change to the account itself.
$group = New-ADGroup -Name $GroupName -GroupScope Global -GroupCategory Security -Path $GroupPath -PassThru
Write-Host "Created group $GroupName."

$cesShort = $CesHost.Split('.')[0]
Add-ADGroupMember -Identity $group -Members (Get-ADComputer -Identity $cesShort)
Write-Host "Added $cesShort to $GroupName."

# CES is reached over HTTP(S), so it needs HTTP SPNs on both the FQDN and the
# short name for Kerberos authentication to succeed either way the client asks.
# CES impersonates the requesting user when it submits to the CA, so it also
# needs constrained delegation to the CA's RPC interface - without that,
# authentication to IIS succeeds but the request fails once it leaves the web
# service.
New-ADServiceAccount -Name $Name `
    -DNSHostName $CesHost `
    -Description 'Runs the AD CS Certificate Enrollment Web Service' `
    -PrincipalsAllowedToRetrieveManagedPassword $group `
    -ServicePrincipalNames @("HTTP/$CesHost", "HTTP/$cesShort") `
    -KerberosEncryptionType AES128, AES256
Set-ADServiceAccount -Identity $Name -Replace @{
    'msDS-AllowedToDelegateTo' = @("rpcss/$CaHost", "HOST/$CaHost")
}
Write-Host "Created gMSA $Name."

$account  = (Get-ADDomain).NetBIOSName + '\' + $Name + '$'
$caConfig = $CaHost.Split('.')[0] + '\' + $CaName

Write-Host ""
Write-Host "Next, on $CesHost (as an administrator):"
Write-Host ""
Write-Host "  # the host must refresh its Kerberos ticket to see the new group membership"
Write-Host "  Restart-Computer"
Write-Host ""
Write-Host "  Install-WindowsFeature ADCS-Enroll-Web-Svc -IncludeManagementTools"
Write-Host "  Install-ADServiceAccount -Identity $Name"
Write-Host "  Test-ADServiceAccount    -Identity $Name     # must return True before continuing"
Write-Host ""
Write-Host "  Install-AdcsEnrollmentWebService -CAConfig '$caConfig' -AuthenticationType Kerberos -ServiceAccountName '$account' -SSLCertThumbprint '<thumbprint>'"
Write-Host ""
Write-Host "If that cmdlet rejects the gMSA, install CES with a normal account and then"
Write-Host "set the CES application pool identity to $account in IIS Manager."
