<#
.SYNOPSIS
    Creates the AD account cert-manager enrols as, and grants it Enroll on the
    certificate template.

.DESCRIPTION
    Run on a domain controller, or any domain member with RSAT-AD-PowerShell, as
    a member of Domain Admins.

    The adcs-issuer authenticates to /certsrv as this account and asks the CA for
    certificates from ADCS_TEMPLATE. The CA refuses unless the account has Enroll
    on that template, so creating the user is only half the job - the stock
    WebServer template grants Enroll to Domain Admins and Enterprise Admins only.

    You are prompted for the password. It is typed into this script, used once to
    create the account, and not written anywhere. The same password goes into the
    cluster later, when configure-clusterissuer.sh prompts for it.

    Safe to re-run: an existing account is left alone and only the template
    rights are granted, so this is also the way to fix up an account created by
    hand.

.NOTES
    Granting Enroll is preferable to putting the account in Domain Admins, which
    would also work and is how it is often done. The issuer needs to request one
    kind of certificate; it does not need to administer the domain.
#>

# Site values live in adcs.env (generated by bootstrap.py from config.env);
# this script is ordinary PowerShell and is meant to be edited directly.

[CmdletBinding()]
param(
    # adcs.env to read. Defaults to $env:ADCS_ENV_FILE, then adcs.env
    # beside this script.
    [string]$ConfigFile,

    [string]$User,
    [string]$Template,
    [string]$Path
)

$ErrorActionPreference = 'Stop'

# Site values come from adcs.env, so this file stays generic. Anything passed
# on the command line wins over the file.
$cfg = & "$PSScriptRoot\Get-AdcsConfig.ps1" -ConfigFile $ConfigFile -Require @('ADCS_ENROLL_USER', 'ADCS_TEMPLATE', 'AD_SERVICE_ACCOUNT_DN')
if (-not $User)     { $User     = $cfg.ADCS_ENROLL_USER }
if (-not $Template) { $Template = $cfg.ADCS_TEMPLATE }
if (-not $Path)     { $Path     = $cfg.AD_SERVICE_ACCOUNT_DN }

Import-Module ActiveDirectory

# ------------------------------------------------------------------- account

if (Get-ADUser -Filter "SamAccountName -eq '$User'") {
    Write-Host "$User already exists - leaving it alone, and granting Enroll below."
} else {
    $password = Read-Host -AsSecureString "Password for $User"
    $domain   = (Get-ADDomain).DNSRoot

    New-ADUser -Name $User `
        -SamAccountName $User `
        -UserPrincipalName "$User@$domain" `
        -Path $Path `
        -AccountPassword $password `
        -Description 'cert-manager adcs-issuer enrolment account' `
        -Enabled $true `
        -PasswordNeverExpires $true
    Write-Host "Created $User in $Path."
}

# --------------------------------------------------------------------- enroll

# Certificate templates are AD objects, and Enroll is an extended right on them
# identified by this well-known GUID. Read is granted alongside it because the
# account has to be able to see the template to request from it - that is the
# pair the Certificate Templates console adds when you tick "Enroll".
$ENROLL_RIGHT = [guid]'0e10c968-78fb-11d2-90d4-00c04f79dc55'

$configNC   = (Get-ADRootDSE).configurationNamingContext
$templateDN = "CN=$Template,CN=Certificate Templates,CN=Public Key Services,CN=Services,$configNC"
if (-not (Test-Path "AD:$templateDN")) {
    throw "Certificate template '$Template' not found at $templateDN."
}

$sid = (Get-ADUser -Identity $User).SID
$acl = Get-Acl -Path "AD:$templateDN"

$acl.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule(
    $sid,
    [System.DirectoryServices.ActiveDirectoryRights]::GenericRead,
    [System.Security.AccessControl.AccessControlType]::Allow)))

$acl.AddAccessRule((New-Object System.DirectoryServices.ActiveDirectoryAccessRule(
    $sid,
    [System.DirectoryServices.ActiveDirectoryRights]::ExtendedRight,
    [System.Security.AccessControl.AccessControlType]::Allow,
    $ENROLL_RIGHT)))

Set-Acl -Path "AD:$templateDN" -AclObject $acl
Write-Host "Granted $User Read + Enroll on the '$Template' template."

# --------------------------------------------------------------------- verify

$granted = (Get-Acl -Path "AD:$templateDN").Access | Where-Object {
    $_.ObjectType -eq $ENROLL_RIGHT -and $_.AccessControlType -eq 'Allow'
} | ForEach-Object { $_.IdentityReference.Value }

Write-Host ""
Write-Host "Enroll on '$Template' is now held by:"
$granted | Sort-Object -Unique | ForEach-Object { Write-Host "  $_" }

Write-Host ""
Write-Host "Use the same password when configure-clusterissuer.sh prompts for it."
