#!/bin/bash
#
# dump-kasm-creds.sh - write the credentials the Kasm chart generated to a file.
#
# With kasmSecrets.passwords left empty the chart generates random values on
# install, so the only copy lives in the cluster. This reads them back and
# writes them to secrets/ - gitignored, mode 600, and never echoed. Print it
# yourself when you want to read it:
#
#   cat secrets/kasm-credentials.env
#
# Re-run after a reinstall: a fresh install generates new values and the old
# file is then wrong.
#
# Usage:
#   scripts/helm/kasm-workspaces/dump-kasm-creds.sh
#   scripts/helm/kasm-workspaces/dump-kasm-creds.sh --print   # to stdout instead
#
set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/../../../lib/config.sh"

NAMESPACE="${KASM_NAMESPACE:-kasm-workspaces}"
RELEASE="${KASM_RELEASE:-kasm-workspaces}"
SECRET="${RELEASE}-secrets"
OUT="${KASM_CREDS_FILE:-$REPO_ROOT/secrets/kasm-credentials.env}"

PRINT=0
[[ "${1:-}" == "--print" ]] && PRINT=1

die() { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

command -v oc >/dev/null || die "oc not found in PATH"
oc whoami >/dev/null 2>&1 || die "oc is not authenticated - run scripts/okd/create-oc-token.sh"
oc get secret "$SECRET" -n "$NAMESPACE" >/dev/null 2>&1 \
  || die "secret $SECRET not found in namespace $NAMESPACE - has the chart been installed?"

# Decode every key rather than a fixed list, so a chart that adds one does not
# silently drop it here. `name` and `namespace` are chart bookkeeping, not
# credentials.
BODY=$(oc get secret "$SECRET" -n "$NAMESPACE" -o json | python3 -c '
import base64, json, sys
data = json.load(sys.stdin).get("data", {})
skip = {"name", "namespace"}
for key in sorted(k for k in data if k not in skip):
    value = base64.b64decode(data[key]).decode("utf-8", "replace")
    print("%s=%s" % (key.upper().replace("-", "_"), value))
')

[[ -n "$BODY" ]] || die "$SECRET contains no credential keys"

HEADER="# Kasm Workspaces credentials, read from secret/$SECRET in namespace $NAMESPACE.
# Generated by scripts/helm/kasm-workspaces/dump-kasm-creds.sh on $(date -Is).
# Regenerate after a reinstall - a fresh install creates new values.
#
# Sign in at https://${KASM_PUBLIC_ADDR:-<publicAddr>}/ as admin@kasm.local with
# ADMIN_PASSWORD below (user@kasm.local uses USER_PASSWORD), unless
# kasmConfig.adminUsername was changed."

if (( PRINT )); then
  printf '%s\n\n%s\n' "$HEADER" "$BODY"
  exit 0
fi

mkdir -p "$(dirname "$OUT")"
# Locked down before anything is written, so the values are never briefly
# world-readable.
install -m 600 /dev/null "$OUT"
printf '%s\n\n%s\n' "$HEADER" "$BODY" > "$OUT"

printf 'wrote %s (mode 600, %s credentials, not echoed)\n' "$OUT" "$(printf '%s\n' "$BODY" | wc -l)"
